### ISSUE TITLE
No license declaration

### ISSUE THREAD

**Issue by rekado** [zhanxw/anno#2]
I would like to package anno for GNU Guix, but unfortunately I cannot find any license declaration in any of the sources.

Could you please add license headers and/or a statement to clarify under what license this application is released?

Thank you!

**Comment by zhanxw** [comment]
Thanks for this question.
I plan to use GPLv3.

**Comment by rekado** [comment]
That is great!  Will you be adding license headers to the files as well or add a note in the repository that all files are covered under GPLv3 or later?

**Comment by zhanxw** [comment]
Done :)

**Comment by rekado** [comment]
@zhanxw Thank you!

Does "GPL version 3, or later" to anno or do you explicitly restrict it to version 3 only?  The terse note in COPYING implies the latter.

(While it may seem pedantic, having this upgrade clause greatly simplifies license compatibility with other GPL software: https://www.gnu.org/licenses/gpl-faq#VersionThreeOrLater)

**Comment by zhanxw** [comment]
Thanks for the info. I can go with "GPL version 3, or later".
