### ISSUE TITLE
Required files

### ISSUE THREAD

**Issue by michaelpreuss** [zhanxw/anno#7]
I'm not able to download the required files like
hs37d5.fa
codon.txt
priority.txt
I got an 404 error.

**Comment by orangeSi** [comment]
dir `example/` has the files, and the reflat format is like `http://rohsdb.cmb.usc.edu/GBshape/cgi-bin/hgTables?hgsid=5145653_ysOMqJKAGhVdkIq2QaJGrg5Tmru1&hgta_doSchemaDb=hg19&hgta_doSchemaTable=refFlat`

**Comment by michaelpreuss** [comment]
thank you.

**Comment by zhanxw** [comment]
Please use: 

http://qbrc.swmed.edu/zhanxw/software/anno/resources/hs37d5.fa
http://qbrc.swmed.edu/zhanxw/software/anno/resources/hs37d5.fa.fai
http://qbrc.swmed.edu/zhanxw/software/anno/resources/refFlat_hg19.txt.gz
http://qbrc.swmed.edu/zhanxw/software/anno/codon.txt
http://qbrc.swmed.edu/zhanxw/software/anno/priority.txt
